#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          rpcmqd 
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RPCmq service
# Description: This script will start rpcmq daemon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="rpcmqd daemon"
NAME=rpcmqd
DAEMON="/usr/sbin/rpcmqd.py"
PIDFILE=/opt/rpc-scripts/run/rpcmqd

. /lib/lsb/init-functions

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Check if AUTOSTART = "" then daemon is disabled
if [ -z $AUTOSTART ]; then
    echo "rpcmqd daemon is disabled in /etc/default/rpcmq"
    echo
    exit 1
fi

case "$1" in
    start)
        echo -n "Starting RPC messaging daemon:" "rpcmqd "
        for NAME in $AUTOSTART ; do
            if [ ! -e $PIDFILE-$NAME.pid ]; then
                echo -n "$NAME "
                $DAEMON -c /etc/rpcmq/rpcmqd-$NAME.conf 
            else
                echo 
                echo "Pidfile already exit $PIDFILE-$NAME.pid"
                exit 1
            fi
        done
        echo
        ;;
    stop)
        echo -n "Stopping RPC messaging daemon:" "rpcmqd "
        for NAME in $AUTOSTART ; do
            echo -n "$NAME "
            kill `cat /opt/rpc-scripts/run/rpcmqd-$NAME.pid`
        done
        echo
        ;;
    restart)
        echo "Restarting RPC messaging daemon:" "rpcmqd"
        $0 stop
        $0 start
        ;;
    status)
        for NAME in $AUTOSTART ; do
            status_of_proc -p $PIDFILE-$NAME $DAEMON $NAME && exit 0 || exit $?
        done
        ;;
    *)  log_action_msg "Usage: /etc/init.d/rpcmqd {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
