#!/bin/bash

# Verify if rpcmq group exist
groupmod rpcmq &> /dev/null
if [ $? == 6 ] ; then
        groupadd rpcmq
fi

# Verify of rpcmq user exist
usermod rpcmq &> /dev/null
if [ $? == 6 ]; then
	useradd -g rpcmq -s /bin/false rpcmq
fi

chmod 750 /usr/sbin/rpcmqd.py
chmod 770 /opt/rpc-scripts/run /opt/rpc-scripts/log
chown -R rpcmq:rpcmq /usr/sbin/rpcmqd.py /opt/rpc-scripts/run /opt/rpc-scripts/log

# Add to runlevel
update-rc.d rpcmqd defaults
